export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_TEAM_SUCCESS = "REGISTER_TEAM_SUCCESS";
export const REGISTER_TEAM_FAIL = "REGISTER_TEAM_FAIL";
export const REGISTER_PLAYER_SUCCESS = "REGISTER_PLAYER_SUCCESS";
export const REGISTER_PLAYER_FAIL = "REGISTER_PLAYER_FAIL";
export const START_MATCH_SUCCESS = "START_MATCH_SUCCESS";
export const START_MATCH_FAIL = "START_MATCH_FAIL";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_FAIL = "FETCH_TEAM_FAIL";
export const FETCH_PLAYER_SUCCESS = "FETCH_PLAYER_SUCCESS";
export const FETCH_PLAYER_FAIL = "FETCH_PLAYER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
